### ISSUE TITLE
Construct from string or operator>> (deserialization)

### ISSUE THREAD

**Issue by le-migou** [nholthaus/units#102]
While the compile-time UDL initialization is nice, reading values from streams at run-time (e.g. from a configuration file) would be quite useful. Do you plan anything of the sort?

**Comment by nholthaus** [comment]
Serialization would be incredibly useful for the library. However, since all information about the unit is stored in the type itself, and the type is lost upon serialization, I haven't figured out a performant, generic way to serialize units. I'd like to, but I'm not totally convinced it can be done.

My lame workaround is I usually pick some canonical units for serialization and just store the double component, which obviously requires a-priori knowledge of the type for deserialization.

**Comment by nholthaus** [comment]
I'm going to take a stab at this for version 3.0. It may be possible to recover the type info with a "virtual constructor" type pattern.

**Comment by nholthaus** [comment]
I spent a good deal of time investigating this, because it would be a really useful feature, but there is just no way to do it in c++17 due to the lack of reflection. We can't put the types back on units once we erase them.

Maybe we can try again when a future standard is released.

**Comment by johelegp** [comment]
Sorry for not posting this earlier, but did you check the C++20 `std::chrono::duration` [IO](https://wg21.link/time.duration.io) functions?

**Comment by nholthaus** [comment]
no... link is dead though

**Comment by johelegp** [comment]
Fixed.

**Comment by johelegp** [comment]
I think I'll try implementing this once I familiarize myself more with [{fmt}](https://github.com/fmtlib/fmt/), its standardization proposal https://wg21.link/P0645, and https://wg21.link/time.duration.io.

**Comment by nholthaus** [comment]
Is it just me or does chrono only serialize? I didn't see an `operator>>`, which I think would require reflection.

**Comment by johelegp** [comment]
That's right. It only serializes `duration`s with `operator<<`. The formatting functions only (de)serialize dates, from what I understand.

I thought we could support deserializing by reading the abbreviation as well. For example, given "20.5 mm", `std::cin >> m` could check that `m`'s type is convertible from the type suggested by the "mm" abbreviation, and calculate the run-time ratio required by the conversion.
