### ISSUE TITLE
Some single-letter symbols are already defined on GCC-ARM

### ISSUE THREAD

**Issue by pvaibhav** [nholthaus/units#31]
On GCC-ARM, ctypes.h apparently already defines _N, _C, _S and _L. Due to this, dropping units.h in an embedded ARM project causes build errors.

I was able to get it to compile by adding:
```
#undef _N
#undef _C
#undef _S
#undef _L
```
Though I'm not sure it's a good solution.

There's a stackoverflow post from 2 years ago with exactly the same problem:
http://stackoverflow.com/questions/23365562/compilation-failure-with-simple-user-defined-literal

The [offending ctype.h is here](https://github.com/nholthaus/units/files/568874/ctype.h.txt)
It defines:
```
#define	_U	01
#define	_L	02
#define	_N	04
#define	_S	010
#define _P	020
#define _C	040
#define _X	0100
#define	_B	0200
```
so we can expect more clashes.

**Comment by nholthaus** [comment]
I'm assuming those are macros?

I'll have to think about that. I can sort of replicate the problem with the windows API which defines a `_T` macro, which originally conflicted with the Tesla definition. There was a [reddit comment](https://www.reddit.com/r/cpp/comments/59r1kc/compiletime_headeronly_dimensional_analysis_and/d9atte6/) which had a suggestion for de-conflicting user-defined literals and macros which I can try out.

If not I'm personally not opposed to the `#undef`s. It can be documented, and I tend to think the people who macro-ize their code are not the same people looking for type-safe c++14 libraries.

**Comment by nholthaus** [comment]
Also, would you mind copy/pasting the original `ctype.h` definitions into the issue? I can try to define them manually and come up with some unit testing.

**Comment by pvaibhav** [comment]
To be fair symbols starting with underscore and uppercase letter are reserved by the C++ standard. I expect more clashes on other platforms. We need to find a solution that scales. Personally I would remove the underscore, don't mind writing literals as `12.0V` or `13.32mA` myself :)

**Comment by nholthaus** [comment]
Yikes, that was a big oversight on my part. I should have [googled it](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier). I think we probably have to do that, but I'll have to rev the version to 3.x since it will break every single piece of code currently using the library.

And then I think if I'm going to change the interface so destructively, I might also move the `_t` suffix from the unit container types to the unit tag types (and probably change it to `_tag` as well).

**Comment by pvaibhav** [comment]
I agree, perhaps a quick documentation update is enough for v2.2.x, directing users to `#undef` any clashing symbols.

**Comment by nholthaus** [comment]
Yup, I think I'll put out 2.2 as the last release with that interface, and I should be able to roll out a 3.0 relatively quickly.

@martinmoene as a fellow unit conversion aficionado, I'm curious if you have any thoughts on this proposed interface change? It may also be an issue in [PhysUnits-CT-Cpp11](https://github.com/martinmoene/PhysUnits-CT-Cpp11).

**Comment by martinmoene** [comment]
[PhysUnits-CT-Cpp11](https://github.com/martinmoene/PhysUnits-CT-Cpp11) does have the same issue. 

Note that UDLs are in namespace `units::literals` and only might clash when `using` (necessary to use them) and `using` something else that contains the same name(s).

I'd much like to see this units library evolve into a proposal for C++ standardization. As such it might be written as `std::experimental::quantity`, nullifying the issue ;)

**Comment by EvanBalster** [comment]
So it looks like the developer is already on top of this, but there's a C++14 feature that solves this issue.  If there's no space after the quotes in the definition (ex.) `operator ""_T`, then the macro `_T` is not expanded.  This allows the use of reserved words as literal suffixes.

See here for details:  http://en.cppreference.com/w/cpp/language/user_literal  (search for "defined-string")

**Comment by nholthaus** [comment]
@EvanBalster so a few people have made that comment to me, but that's how the library is currently implemented and I've had existential problems when including `<Windows.h>` with VS2015 and having the macro still clash. Maybe it's just a bug on their end, and maybe gcc-arm isn't fully c++14 compliant?

@pvaibhav so I think in the end I'm actually _not_ going to change the UDLs because there's [a requirement](http://en.cppreference.com/w/cpp/language/user_literal) that suffixes must begin with an underscore, which kind of ruins our whole idea. Additionally, per @EvanBalster 's comment, UDLs are intended to be able to override underscore + capital letter (at least with a fully conformant c++14 compiler).

I still plan make the documentation update (eventually), and I'll probably change `_Te` to `_T` and just warn the user to `undef` it.

**Comment by nholthaus** [comment]
This is now going to go into v2.2.0 as a documentation change, which warns about some known `#undef` statements that will have to be made when compiling with c++11.
