### ISSUE TITLE
How to get the unit value with correct scaling ?

### ISSUE THREAD

**Issue by Lecrapouille** [nholthaus/units#335]
Hello

```
  meter_t d = 10_km;
  std::cout << d.value() << std::endl;
```

Will display `10000` (meters). I cannot find the method that will return `10` (something like `d.value<km>()`). Any idea ?

**Comment by chiphogg** [comment]
Is this because you're writing `meter_t d` instead of `auto d`, thereby requesting an implicit unit conversion to meters?

In any case, `.value()` is code smell, for the reasons you've encountered.  It means "give me the underlying numeric value of the quantity in its current units, regardless of what those units are".  And when is that really what you want?

I don't think there's an interface in nholthaus like `d.value<km>()`.  I assume the closest thing you could get would be `kilometer_t{d}.value()` (although I haven't tested that).

If you're open to [alternatives](https://aurora-opensource.github.io/au/main/alternatives/), there are other libraries that provide interfaces like what you suggest.  When the function that gives you the underlying value lets you specify the unit, that's a "unit safe interface".  I know of two C++ units libraries that provide this: [mp-units](https://github.com/mpusz/mp-units) (C++20 minimum), and [Au](https://github.com/aurora-opensource/au) (C++14 minimum).  (Full disclosure: I wrote and maintain Au, and I have contributed to mp-units.  Also, the alternatives comparison above is part of Au's documentation website.)

**Comment by Lecrapouille** [comment]
Thank you. So it is the same behavior than count() of std::chrono. Fine for me in this case.

```
std::chrono::milliseconds(10).count(); // 10

std::chrono::seconds(10).count(); // 10
```

I'm using value() to "cast" physical value into bitfield struct for encoding and decoding CAN frames. I was scared your lib always  convert to the based unit (0.01 instead of 10).

I'm aware for others libs. I used yours positively long time ago and I'm stucked with the C++ version of the standard.

**Comment by chiphogg** [comment]
> I'm using value() to "cast" physical value into bitfield struct for encoding and decoding CAN frames. I was scared your lib always convert to the based unit (0.01 instead of 10).

Well, I can clear that up.  :slightly_smiling_face:  In Au, we can store values in any unit, so making something like `kilo(meters)(10)` (or, equivalently, `10 * km`) will store an underlying value of `10`, annotated with units of kilometers.

We'll only do unit conversions if you ask for them, either by calling something like `.in(m)` or `.as(meters)`, or by assigning to a quantity of, say, meters, when that conversion is safe.  And we _never_ convert to the "base" unit, because there are no privileged units in Au: they all come in on an equal footing.

In case you were worried about a call to `.in(km)` performing a conversion, we have an alternative that is guaranteed not to convert: `.data_in(km)` provides a **reference** to the underlying raw numeric value, and it won't compile unless the unit is equivalent to km.  This is nice because not only does it better express author intent, but it also keeps you safe from errors that can arise during refactoring (for example, if you change the initial variable to be in `m` instead of `km`).

> I'm aware for others libs. I used yours positively long time ago and I'm stucked with the C++ version of the standard.

Glad to hear you had a positive experience!  As far as C++ standards go, Au's C++14 minimum requirement is the same as for nholthaus units.
