### ISSUE TITLE
Typedef notation for underlying number types

### ISSUE THREAD

**Issue by EvanBalster** [nholthaus/units#40]
Hello!

As an option for the library, it would be quite useful to generate typedefs for multiple number formats in one project.  Currently the library only defines `_t`-suffixed typedefs with an underlying type defined by UNIT_LIB_DEFAULT_TYPE.  I propose supporting common or possibly user-defined number types with other type suffixes.  Macro-generated names might look like this:

```
using meter_i = unit_t<meter, int>;
using meter_f = unit_t<meter, float>;
using meter_d = unit_t<meter, double>;
```

As an example use-case, I might represent (absolute) points in a simulated world using fixed-point values at the millimeter scale, and vectors using floating-point values at the meter scale.  I may have certain numerically-unstable math here and there which I wish to promote to double-precision, in a project otherwise using single precision.

I suspect this should be optional, and disabled by default, to avoid code bloat.

**Comment by nholthaus** [comment]
I have some mixed feelings about this, although I agree that you are right that there are use-cases for non `double` underlying types.

## floating point

For floating point, you really only have a choice between `float` and `double`. I did some experimentation with `long double` in a geodesy library I built on top of `units`, and found that the rounding errors were significantly more of a problem then when using `double`, while the additional precision didn't buy anything (presumably because `double` can use the extra register space to store data that will later be truncated, while `long double` can't). My opinion is that there's not a use case for it, at least on x64.

`float` can definitely be useful for gaming or CUDA/GPU processing, but I think in most cases you'd want to set `UNIT_LIB_DEFAULT_TYPE` because either you don't care about the precision or it's dictated by your hardware. While valid, I'm not sure your use-case would work as well as you think, because mixing units with different underlying types (especially int/double) isn't always possible (at least as currently implemented). It's an unfortunate by-product of using the strong typing to enforce dimensionality but having the underlying type be a part of the type definition as well (which we don't care so much about enforcing). Some half-hearted attempts I made to get around the typing problem weren't successful, although my instinct is that it could be done. _I'd definitely take a PR for it if someone was sufficiently motivated._

## integral

The only time I personally have seen the need for integer types is when interfacing with hardware registers when I wanted to be absolutely sure that the bits being written were exactly the way I wanted them (surprisingly, units is actually pretty friendly for embedded applications). In those cases I just made a quick alias `using meter_i = unit_t<meter, int>;` and left the `UNIT_LIB_DEFAULT_TYPE` as `double` (to avoid integer division).

The library is intentionally compatible with integral types, but there are a _lot_ of limitations due to their nature. For one, arithmetic overflow is a serious problem and really limits the usable range of values. 64 bit (or larger) numbers are basically unusable. Also, in the general case, you need to stick with signed values so all the math works as expected. Most importantly, except for pretty basic metric order conversions (e.g. nanoseconds to milliseconds or something), you'll wind up doing integer division in the conversions and getting off-the-wall values, especially if things end up getting cascaded. 

So I kind of see the lack of supplied integral types as a feature/design, since they won't 'work' in the general case. If you really do want them, and have a limited enough use case where you know they will work, you can easily make the typedef as you alluded to. That said, I do it enough that I find it to be pretty annoying, so I know where you are coming from.

## what I recommend

Make your own type-alias when you need specialty underlying types. Changing the `UNIT_LIB_DEFAULT_TYPE` to `float` is safe, but avoid setting it to integral types unless you're happy with pure integral arithmetic.

**Comment by nholthaus** [comment]
@EvanBalster I'm going to close this, but we can reopen if you find problems with the rationale.

**Comment by GElliott** [comment]
I'd like to reopen this feature request (or something similar).  I have three use-cases where a blanket change to `UNIT_LIB_DEFAULT_TYPE` would be problematic:

1. I work on code base shared by server-class and embedded-class processors.  The embedded processors may not have a floating point unit, let alone one that supports double precision floating point.  For the embedded processors, I only want to use double-precision when it is necessary (it sometimes is), but I usually want to stick to single-precision for two reasons: (1) available flash and RAM is measured in 100s of K---significant memory savings are had by defaulting to single-precision; and (2) software-based single-precision is less costly than software-based double-precision.  (In many respects, the embedded processor benefits the most from units-based type checking, since it fulfills safety-related roles.)
2. There are co-processors (e.g., NVIDIA GPUs running CUDA), where major performance gains can be realized by using half-precision floating point.  Both the CPU-side and GPU-side code would need to be able to declare half-precision `units::` types, but I don't want to prevent CPU-side code from also making use of double-precision `units::`.
3. I would like to be able to specify `units::` types in message passing data structures.  With efficient bandwidth utilization in mind, it makes sense to use the smallest underlying data type necessary.  Data can be marshaled manually (`msg.field = a_unit.to<float>()`), but that requires boilerplate code, which may require the use of code generation if messages are too numerous or too complex.  (In fact, I am in this situation now.  My code generator parses message descriptions, and generates the `units::`-to-field-type and field-type-to-`units::` message packing/unpacking routines.  It would have been much nicer if I could have just declared a standard-layout C++ struct.)

It would be nice if there were a way to easily declare the underlying representation.  Also, it would be nice if there was an easy way to switch between representations (i.e., assign a float-based unit type to a double-based unit type and visa versa).  I tend to think that `std::chrono` went overboard with `duration_cast`---it really makes for ugly code.

My apologies if this is already supported.  I'm happy to implement my own typedefs of `units::` types to declare representations (e.g., `meters_fp16_t` for half-precision, and `meters_fp32_t` for single-precision), but it's not clear to me how this can be done.
