### ISSUE TITLE
pascal defined elsewhere

### ISSUE THREAD

**Issue by JaapAap** [nholthaus/units#54]
I just ran into the issue (on VS2015) that the header minwindef.h (that is pulled in from somewhere, not sure where) defines this:

#if (!defined(_MAC)) && ((_MSC_VER >= 800) || defined(_STDCALL_SUPPORTED))
#define pascal __stdcall
#else
#define pascal
#endif

which obviously conflicts with defining pascal as a unit.

**Comment by nholthaus** [comment]
my advice has been to `#undef` unused clashing macros before the inclusion of `<units.h>`. I `#undef pascal` in a bunch of my code (and haven't any issues).

I can at least add it to the list of known clashes.

I'd be open to better ideas for dealing with the clashes (for example using `_Te` as the tesla abbreviation because that macro is baked into MSVC and can't be undefined seemingly), but renaming the units/abbreviations appeases half the user base and upsets the other half.

**Comment by MikeGitb** [comment]
I thought any identifier starting with `_[Capital Letter]` is reserved for use by the c++ implementation. Does that not apply to suffixes?

**Comment by nholthaus** [comment]
So I changed my mind and will pop the pascal macro in v2.3
