### ISSUE TITLE
Would anyone miss Visual Studio 2013 support if it was gone?

### ISSUE THREAD

**Issue by nholthaus** [nholthaus/units#61]
My original intention was to support `Visual Studio 2013` through the `v2.x.x` series of releases. However, the library is becoming increasingly difficult to maintain because of the hoops and basically occult practices required to avoid dreaded `internal compiler errors`. In addition, I'm not sure that the test cases adequately reflect whether an ICE error will occur _in user code_.

VS2013 was originally supported because of a lack of CUDA/Qt support for VS2015, which has long since been remedied. It won't continue to be possible for long as support for C++17 features are rolled in.

So, I'm wondering if VS2013 support was discontinued in the `v2.x.x` series of releases (i.e. in version 2.3.0) would anyone actually care?

**Comment by mwu-tow** [comment]
I'm fine with leaving only VS 2015 support.

**Comment by JaapAap** [comment]
While I personally would not care, it is hard to speak for 'anyone'. When there is a clear advantage in dropping support, and effort can be better focussed when doing so, that would clearly support your 'drop unless' approach

**Comment by nholthaus** [comment]
Basically it's getting exponentially harder to maintain, as VS2013 suffers from an abundance of "internal compiler error", and continued support often relies on using obtuse template syntax that contributors often "fix" in their PRs. If none of my (active) users seem to care, then I'll probably support it as long as I don't have to go out of the way to do so, but if some c++14 feature kills it, then so be it.

**Comment by MikeGitb** [comment]
Considering, that the community editions of VS2015 and VS2017 are freely available and VS2013 comes nowhere close to full c++11 support I'd guess that most people have switched to a newer version of VS by now. The question is also, if there are any important features/bugfixes in the pipeline for the next versions that the remaining VS2013 users would be cut-off from or are they more nice-to-have things? After all it's not like a VS2013 user can't use your library anymore once support is dropped - he just can't use the new versions of it.

**Comment by stefan-muc** [comment]
Yes, here am I! I would miss it as I still use Visual Studio 2013 compiler. If you have a larger codebase with several developers, you usually don't switch compilers too often, because you would have to change your complete infrastructure (including build servers), so there am I with Visual Studio 2013

On the other side I don't see why you should have exponentially harder work by supporting a four year old compiler with new features of this library. There's just one thing I would really miss: Reduced compile time which is already checked in for 2.3.x (I didn't test it, just read the commit log). With 2.2.0 on Visual Studio 2013 I have compile time of around one minute, that's too much.

My recommendation would be:
Develop and release 2.3.0 with reduced compile time but Visual Studio 2013 support. Do a "feature freeze" for 2.3.x
Start a new version (2.4.x / 3.x) without Visual Studio 2013 support and new features.

I want to thank you for you library! To use the words of a friend of mine: "that's crazy shit"
Sadly I can't yet use the literals, but even the other parts of the library are amazing! Thank's for Visual Studio 2013 support.

**Comment by nholthaus** [comment]
@stefan-muc OK, good to know someone cares :) Thank you and your friend for the kind words!

The reason it's harder in Visual Studio 2013 is not the compiler's (relatively young) age, but that it's not C++14 feature complete, and is incredibly buggy in its C++11 implementation, with the result that valid units library code often causes "internal compiler errors" on vs2013 that don't appear in vs2015, gcc, clang, etc... and the workaround is usual to write very archaic template code that either takes days to figure out the magic combination, or doesn't exist at all.

At this point I'm not doing anything to specifically support, or not support vs2013. I expect it to be supported in v2.3.0, but that's probably it. I understand your logic about switching compilers (the only reason it ever supported 2013 because it's what I was using at work at the time).

I'd also strongly recommend that you use [v2.3.0 RC 2](https://github.com/nholthaus/units/releases/tag/v2.3.0RC2) for your current development. It compiles a _lot_ faster, and the only difference between this and the impending official v2.3.0 release is a documentation upgrade, and _maybe_ some additional compile-time speedup if I can figure out something that studio can compile. In terms of testing/QA, it's had the same treatment as all the other releases.

**Comment by stefan-muc** [comment]
@nholthaus Thanks for your long reply! I fully understand it, keep going this direction!

Oh yeah, I tested v2.3.0 RC 2 and it indeed is a lot faster. I like it, thanks!
