### ISSUE TITLE
Conversion between Celsius and Kelvin seems to fail

### ISSUE THREAD

**Issue by guarndt** [nholthaus/units#75]
Hi Nic, I have recently added your library to my project to convert a Platinum sensor's resistance to its temperature. I like the library especially because the std::math functions have been ported, but there is one issue I stumbled across yesterday when performing the mentioned conversion. It required the square root of a value given in °C² to be calculated. That should give a result in °C, but seems to convert to Kelvin in between, and not to convert back correctly.
The following code reproduces the problem:
`using squared_celsius = units::compound_unit<squared<celsius>>;`
`using squared_celsius_t = units::unit_t<squared_celsius>;`
`const squared_celsius_t right(100);`
`const celsius_t rootRight = units::math::sqrt(right);`
`std::cerr << rootRight << std::endl;` 
It prints "-263.15 degC", which is 10 K, but in my opinion should print "10 degC".
I use a SysGCC 4.9.2 compiler from Windows to Raspberry Pi Linux.

**Comment by nholthaus** [comment]
I didn't anticipate that type of math and my guess is that the pow/sqrt
operation is throwing away the translation. I'll have to look into it.
Thanks for pointing this out!

**Comment by JaapAap** [comment]
Quite a different issue potentially, but surely fitting under the same 'conversion fails' banner: boost.units has two notions of temperature, which they call 'relative' and 'absolute'. The underlying issue they try to solve is that temperature differences have different associated conversions than absolute temperatures: a difference of 10K equals a difference of 10 degC rather than a difference of -263.15 degC. I don't think that the library contains a notion of temperature differences? This is something really lacking for me at this point (admittedly, the boost.units solution was also problematic sometimes, and this is likely to be  conceptually far from trivial).

**Comment by MikeGitb** [comment]
I wonder if you his could be generalized: You very often want to distinguish between absolute and relative values. E.g. think about std::chrono's duration and time point. Or a location and a distance between two of them.

**Comment by nholthaus** [comment]
This is just a bug in the math that I was hoping wasn't a real use case. Treating absolute and relative temperature differently isn't really in the scope of a units library because they are totally compatible, e.g. you can add a relative temperature to an absolute, etc. That type of stuff really belongs in a vector library that uses units as its base types.

**Comment by JaapAap** [comment]
Not sure what you mean by 'totally compatible', would you suggest that both concepts are currently supported? And what would be the relation to vector arithmetic?

For most units, my understanding is that different scales are linearly related and there really is no distinction between relative and absolute values (i.e., they have the same conversion factor).  'Relative temperature' (that is, temperature differences) also needs linear translations and acts like most other units, while the translation for absolute temperatures is affine. They are not 'compatible' in the sense of other units: while indeed one can add a relative temperature to an absolute one, adding two absolute temperatures does not seem to make much sense, while differencing two absolute temperatures would give a relative temperature. 

Currently, absolute temperatures can still be added, and differencing 20_degC-10_degC gives 10_degC, 20_K-10_k gives 10_K, which should also equal 10_C but it doesn't as the results are treated as absolute values.

**Comment by nholthaus** [comment]
temp translations are fixed in v2.3. Thank you very much for this bug report!

**Comment by guarndt** [comment]
Thank you for the fix.
