### ISSUE TITLE
Conversion may be slower than Boost.Units

### ISSUE THREAD

**Issue by djleach-belcan** [nholthaus/units#89]
I'm intrigued by this library for a number of reasons. One of them is that I assumed, when compiled with optimizations, it would perform faster conversion than Boost.Units due to leveraging `constexpr`. However a simple (and perhaps terrible) benchmark shows that units generates four division instructions on ARM (GCC 5.4 -O3) while Boost.Units generates two. I can provide more details if needed. Is this to be expected?

units test:
```
double BenchmarkSimpleConversion(unsigned times)
{
	auto a = units::length::meter_t{};
	auto b = units::volume::cubic_meter_t{};
	auto c = units::time::second_t{};

	double total{0};
	for (auto i = 1u; i <= times; ++i)
	{
		a = i * 10.0_ft;
		b = units::length::meter_t{double(i)} * units::length::yard_t{double(i)} * units::length::foot_t{double(i)};
		c = units::time::second_t{double(i)};

		auto rate = a / b / c;
		total += rate.to<double>();
	}

	return total;
}
```

Boost.Units test:
````
double BenchmarkSimpleConversion(unsigned times)
{
	typedef quantity<si::meter_base_unit::unit_type> convert_to_m;

	quantity<si::length> a{};
	auto b = quantity<si::volume>{};
	auto c = quantity<si::time>{};

	double total{0};
	for (auto i = 1u; i <= times; ++i)
	{
		a = convert_to_m(i * 10.0 * ft);
		b = (si::meter * i) * convert_to_m(i * yd) * convert_to_m(i * ft);
		c = i * si::second;

		auto rate = a / b / c;
		total += rate.value();
	}

	return total;
}
````

**Comment by nholthaus** [comment]
Sorry it took so long to look into this. I don't have a boost::units testbed so I only looked at it from my end.

I kind of agree that the benchmark is probably terrible. Trying to find a better one, I actually had a hard time writing a test that would generate _any_ machine code. Even if I simply inlined the benchmark function, my compiler optimized the entire thing away. 

That said, you can't really compare the libraries in an apples-to-apples way, because they have very different capabilities. For example, I'd like to see boost do something like this (and generate no machine code):

![image](https://user-images.githubusercontent.com/10323743/39325115-63548ba2-495f-11e8-9ba0-8d2f27c71265.png)

![image](https://user-images.githubusercontent.com/10323743/39325171-83d00654-495f-11e8-89a5-39ed3ed13649.png)

I'm sure that's not the only case where boost::units is marginally faster, but overall units will generate much less total machine code in a program due to its constexpr automations.

**Comment by djleach-belcan** [comment]
Thanks for the response, but I'm not sure we're on the same page. In my example (and real-world use case), quantities `a`, `b`, and `c` are not known until runtime, therefore `constexpr`operations aren't going to help as much. I may take a closer look after inlining the function in question. The application is a real-time control system performing continuous calculations and conversions between units.

**Comment by nholthaus** [comment]
I see. I haven't come across any cases before where no quantities were known until run-time. That's definitely a worst case. I'll have to dig a little more.
